### ISSUE TITLE
Topics for meetings

### ISSUE THREAD

**Issue by stevenlio88** [UBC-MDS/Bank_Marketing_Prediction#20]
Few key discussions:

1. Model scripts process is completed (Included Logistics Regression, Random Forest)
2. Should models be separate and which one do we pick? (We have 2 versions of Logistics Regression)
3. Can / Should EDA scripts be grouped into just one?
4. Are we ready for starting the Final Report?
5. Challenges?

**Comment by mmaidana24318** [comment]
3. Merged EDA scripts in one, per informal discussion in Slack.

**Comment by mmaidana24318** [comment]
RE: 5 - I just created a PR w/ an initial report out. It was easier for me to do it in R markdown, so I hope that works for everybody. We can discuss further in our meeting.
