### ISSUE TITLE
Makefile delete statements

### ISSUE THREAD

**Issue by stevenlio88** [UBC-MDS/Bank_Marketing_Prediction#47]
Hey, I am thinking can we not delete everything in the doc/ results/ folder instead of the specific file?

**Comment by mmaidana24318** [comment]
I thought about that too... I was planning to ask a TA and confirm it because Tiffany showed it file by file.

**Comment by stevenlio88** [comment]
In her example repo, they did both, one is deleting the path and one is specific files. I thought it would be cleaner to delete just the path under results/ and maybe not doc/ I guess.. (there is stuff in doc/ wasn't generated by the scripts. Let's disccuss.

**Comment by stevenlio88** [comment]
Issues have been resolved. See PR #49.
