### ISSUE TITLE
EDA

### ISSUE THREAD

**Issue by mmaidana24318** [UBC-MDS/Bank_Marketing_Prediction#8]
The data set seems to have some features that we may want to drop. 
For instance "duration" for successful calls is huge and would be a clear indicator of the target. However, we wouldn't know the duration of the call in advance in a plausible scenario.

**Comment by stevenlio88** [comment]
I think it will only be a problem for a newly joined customer who may never be contacted (from) the company. But anyone who was contacted at least once will have some value for this variable. I guess this model can be used for customers who have some minimum tenure with the company. Company can initiate a welcome call to a new customer (autodialer) or maybe the new product is already introduced to them when they join the company. But I do agree with you, we can look at the impact of this variable to decide if we should keep it.
